esphome:
  name: serra-up-brain
  includes:
    - moist.h
  libraries:
    - SPI
    - tinyu-zhao/FFT@^0.0.1
    
  
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""
  
switch:
  - platform: gpio
    name: "CH0"
    pin: 
        number: 25
        inverted: true
  - platform: gpio
    name: "CH1"
    pin: 
        number: 5
        inverted: true
  - platform: gpio
    name: "CH2"
    pin: 
        number: 18
        inverted: true
  - platform: gpio
    name: "CH3"
    pin: 
        number: 19
        inverted: true    
  - platform: gpio
    name: "Pompa1"
    pin: 27
  - platform: gpio
    name: "Pompa2"
    pin: 26
  - platform: restart
    name: "SerraUp Restart"    
    
dallas:
  - pin: 25
  
sensor:
  - platform: custom
    lambda: |-
      auto moistSensor = new MoistMCP3201Sensor(14,12,15);
      App.register_component(moistSensor);
      return {moistSensor};
    sensors:
      name: "moist1"
      unit_of_measurement: "UNIT_PERCENT"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: dallas
    address: 0xD601203969EBF428
    name: "SerraUp temperature"  
  - platform: dallas
    address: 0x7C012039EFB20628
    name: "SerraUp temperature2"     
    

wifi:
  ssid: "TP-LINK_2.4"
  password: "caciottinatuttook"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Serra-Up-Brain Fallback Hotspot"
    password: "3kLwe3TbDPgI"

captive_portal:
